# Generated by Django 3.2 on 2022-05-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('acervo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.DateField(auto_created=True, default='27/05/2022')),
                ('data_emprestimo', models.DateField(auto_created=True, default='12/05/2022')),
                ('fk_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='funcionarios.funcionario')),
                ('fk_livro1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='livro1', to='acervo.livro')),
                ('fk_livro2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='livro2', to='acervo.livro')),
                ('fk_livro3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='livro3', to='acervo.livro')),
                ('fk_livro4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='livro4', to='acervo.livro')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
        ),
    ]
