# Generated by Django 3.2 on 2022-05-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_created=True, default='12/05/2022', editable=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='prazo',
            field=models.DateField(auto_created=True, default='27/05/2022', editable=False),
        ),
    ]
