# Generated by Django 3.2 on 2022-05-12 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_alter_emprestimo_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 5, 12)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='prazo',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 5, 27)),
        ),
    ]
